version: '3'
services:

  db:
    container_name: mysql
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: 00000000
    ports:
      - 3306:3306

  app:
    container_name: app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 9999:8080
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker